### ISSUE TITLE
Possibility to add quilt2?

### ISSUE THREAD

**Issue by Midnighter** [conda-forge/quilt-feedstock#25]
Hi,

@eladnoor and I are working on a [feedstock for equilibrator-cache](https://github.com/conda-forge/staged-recipes/pull/12525) which uses the older quilt2 API. We know it's quite old by now but we heavily depend on it. Would it be possible to make a release for quilt < 3.0, please?

Thank you for considering it.

**Comment by knaaptime** [comment]
hey, not conda-forge expert but happy to help if i can. Afaict, since quilt2 is distributed on pypi as `quilt`, whereas quilt3 is on pypi as `quilt3`, i think all you would need to do is create a conda-forge recipe for `quilt`

**Comment by Midnighter** [comment]
I think you're right in principle but since you're distributing it on conda-forge as just quilt maybe we need to make a feedstock for quilt2 instead?

**Comment by akarve** [comment]
Hi. My two cents in this is that the OSS team behind Quilt now only supports quilt3. We won't be able to put any resources into supporting the original Quilt. If at all possible we'd like to help you transition to 3.x and higher. Please find us on slack: slack.quiltdata.com. And we can discuss options.

**Comment by Midnighter** [comment]
Okay, thank you. We'll discuss this option.
